server:
  port: 9000
spring:
  application:
    name: alicloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 84101a18-3105-4a54-a1c2-fb4af48ed848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
      #配置路由规则 每个id是一个路由策略，predicates中可设置多种策略:Before、Between、Cookie、Header、
      ##Host、Method、Path、Query、ReadBodyPredicateFactory、RemoteAddr、Weight、CloudFoundryRouteService
      ## 访问时也可不用加服务名，通过路径前缀匹配 例如：http://localhost:9000/provider/config
      ## http://localhost:9000/service-provider/provider/test
      routes:
        ##自定义id
        - id: service-consumer
          ##负载均衡   和直接设置网址：http://xxxxx
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
        - id: service-provider
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG