server:
  port: 7001
spring:
  application:
    name: auth-service-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      username: nacos
      password: nacos
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7000/user/current
    client:
      id: app
      client-secret: app
      access-token-uri: http://localhost:7000/oauth/token
      grant-type: client_credentials,password
      scope: web
logging:
  level:
    org.spring.security: debug